"""threads outgoing and reply count

Revision ID: 7be9ca6af172
Revises: 5ad4160b7868
Create Date: 2026-09-12 17:03:20.568175

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = '7be9ca6af172'
down_revision: str | Sequence[str] | None = '5ad4160b7868'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('outgoing', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_messages_message_id_hdr', 'messages', ['message_id_hdr'], unique=False)
    op.add_column('sender_profiles', sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('sender_profiles', 'reply_rate')
    op.create_index('ix_threads_user_subject', 'threads', ['user_id', 'subject_norm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threads_user_subject', table_name='threads')
    op.add_column('sender_profiles', sa.Column('reply_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('sender_profiles', 'reply_count')
    op.drop_index('ix_messages_message_id_hdr', table_name='messages')
    op.drop_column('messages', 'outgoing')
    # ### end Alembic commands ###
