"""message is_test flag

Revision ID: c4f9e2ea4455
Revises: 7be9ca6af172
Create Date: 2026-09-12 19:25:35.383277

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = 'c4f9e2ea4455'
down_revision: str | Sequence[str] | None = '7be9ca6af172'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_test', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_test')
    # ### end Alembic commands ###
