"""initial schema

Revision ID: 5ad4160b7868
Revises: 
Create Date: 2026-09-12 12:49:53.241626

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5ad4160b7868'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus', native_enum=False, length=32), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_queued', 'jobs', ['run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Almaty', nullable=False),
    sa.Column('digest_time', sa.Time(), server_default=sa.text("'09:00'"), nullable=False),
    sa.Column('daily_budget_usd', sa.Numeric(precision=10, scale=2), server_default='1.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tg_user_id', name=op.f('uq_users_tg_user_id'))
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_usage_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index('ix_llm_usage_user_created', 'llm_usage', ['user_id', 'created_at'], unique=False)
    op.create_table('mail_accounts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('gmail', 'microsoft', 'imap', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('auth_type', sa.Enum('app_password', 'xoauth2', name='authtype', native_enum=False, length=32), nullable=False),
    sa.Column('secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), server_default='993', nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), server_default='587', nullable=False),
    sa.Column('status', sa.Enum('active', 'auth_failed', 'disabled', name='accountstatus', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mail_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_accounts')),
    sa.UniqueConstraint('user_id', 'email', name=op.f('uq_mail_accounts_user_id_email'))
    )
    op.create_index(op.f('ix_mail_accounts_user_id'), 'mail_accounts', ['user_id'], unique=False)
    op.create_table('sender_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('msg_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reply_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sender_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'address', name=op.f('pk_sender_profiles'))
    )
    op.create_table('threads',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_norm', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_threads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_table('user_rules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('vip', 'mute', 'instruction', name='rulekind', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_rules'))
    )
    op.create_index(op.f('ix_user_rules_user_id'), 'user_rules', ['user_id'], unique=False)
    op.create_table('mailbox_sync',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=False),
    sa.Column('uidvalidity', sa.BigInteger(), nullable=False),
    sa.Column('last_uid', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], name=op.f('fk_mailbox_sync_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'folder', name=op.f('pk_mailbox_sync'))
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('message_id_hdr', sa.String(length=998), nullable=False),
    sa.Column('in_reply_to', sa.String(length=998), nullable=True),
    sa.Column('references', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('from_addr', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('to_addrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cc_addrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), server_default='', nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], name=op.f('fk_messages_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_messages_thread_id_threads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('account_id', 'message_id_hdr', name=op.f('uq_messages_account_id_message_id_hdr'))
    )
    op.create_index('ix_messages_account_folder_uid', 'messages', ['account_id', 'folder', 'uid'], unique=False)
    op.create_index(op.f('ix_messages_account_id'), 'messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_messages_from_addr'), 'messages', ['from_addr'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('text_layer', 'docx', 'html', 'vision', 'none', name='extractionmethod', native_enum=False, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'sent', 'failed', name='draftstatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_drafts_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts')),
    sa.UniqueConstraint('message_id', 'version', name=op.f('uq_drafts_message_id_version'))
    )
    op.create_index(op.f('ix_drafts_message_id'), 'drafts', ['message_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('importance_wrong', 'importance_right', 'draft_edited', 'draft_rejected', name='feedbackkind', native_enum=False, length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_feedback_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_message_id'), 'feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('card', 'digest', 'quarantine', name='notificationkind', native_enum=False, length=32), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_notifications_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_message_id'), 'notifications', ['message_id'], unique=False)
    op.create_table('triage_results',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('needs_reply', sa.Boolean(), nullable=False),
    sa.Column('suspicious', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance BETWEEN 0 AND 3', name=op.f('ck_triage_results_importance_range')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_triage_results_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_triage_results'))
    )
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', content)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_chunks_attachment_id_attachments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_chunks_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chunks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index(op.f('ix_chunks_attachment_id'), 'chunks', ['attachment_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_chunks_message_id'), 'chunks', ['message_id'], unique=False)
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_user_id'), table_name='chunks')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_chunks_message_id'), table_name='chunks')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunks_attachment_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('triage_results')
    op.drop_index(op.f('ix_notifications_message_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_message_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_drafts_message_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_addr'), table_name='messages')
    op.drop_index(op.f('ix_messages_account_id'), table_name='messages')
    op.drop_index('ix_messages_account_folder_uid', table_name='messages')
    op.drop_table('messages')
    op.drop_table('mailbox_sync')
    op.drop_index(op.f('ix_user_rules_user_id'), table_name='user_rules')
    op.drop_table('user_rules')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('sender_profiles')
    op.drop_index(op.f('ix_mail_accounts_user_id'), table_name='mail_accounts')
    op.drop_table('mail_accounts')
    op.drop_index('ix_llm_usage_user_created', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_table('users')
    op.drop_index('ix_jobs_queued', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('jobs')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
