"""user referral

Revision ID: 4ac9aaee3443
Revises: c4f9e2ea4455
Create Date: 2026-09-26 17:48:25.083159

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = '4ac9aaee3443'
down_revision: str | Sequence[str] | None = 'c4f9e2ea4455'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral')
    # ### end Alembic commands ###
